version: '2'

services:

  collabora:
    container_name: collabora
    build: .
    image: sfoxdev/collabora
    restart: always
    ports:
      - 9980:9980
    environment:
      - DOMAIN=localhost
      - USERNAME=admin
      - PASSWORD=password
    cap_add:
      - MKNOD
